[[redirects]]
  from = "https://abos-watchlist.netlify.app/api"
  to = "https://watchlistbackend-production.up.railway.app/api"
  status = 200
  force = true
  signed = "API_SIGNATURE_TOKEN_PLACEHOLDER"